version: '3.9'
services:
  alchilazo-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=alchilazodb 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin
      
    ports:
    - 3306:3306
    command: --init-file /docker-entrypoint-initdb.d/alchilazoDB.sql
    networks:
      - alchilazonet    
    volumes:
      - ./alchilazoDB.sql:/docker-entrypoint-initdb.d/alchilazoDB.sql
      - db_data:/var/lib/mysql

  backend:
    image: tinbrew/alchilazo-backend
    env_file: .env
    restart: on-failure
    networks:
      - alchilazonet
    ports:
      - 4000:4000
    depends_on:
      - alchilazo-db

  frontend:
    image: tinbrew/alchilazo-frontend
    restart: on-failure
    networks:
      - alchilazonet
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  db_data:

networks:
  alchilazonet:
    driver: bridge